/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasiseleksi;

import javax.swing.JOptionPane;

/**
 *
 * @author Lab Informatika
 */
public class Designer extends javax.swing.JFrame {

    /**
     * Creates new form Designer
     */
    public Designer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        SD = new javax.swing.JLabel();
        nama = new javax.swing.JLabel();
        BCP = new javax.swing.JLabel();
        kampus = new javax.swing.JLabel();
        ipk = new javax.swing.JLabel();
        FP = new javax.swing.JLabel();
        porto = new javax.swing.JLabel();
        proto = new javax.swing.JLabel();
        creativity = new javax.swing.JLabel();
        inputNama = new javax.swing.JTextField();
        inputKampus = new javax.swing.JTextField();
        inputIpk = new javax.swing.JTextField();
        inputPorto = new javax.swing.JTextField();
        inputProto = new javax.swing.JTextField();
        inputCreativity = new javax.swing.JTextField();
        nilai = new javax.swing.JButton();
        kembali = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SD.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        SD.setText("Seleksi Designer");

        nama.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        nama.setText("Nama");

        BCP.setFont(new java.awt.Font("News706 BT", 1, 11)); // NOI18N
        BCP.setText("Biodata Calon Pegawai");

        kampus.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        kampus.setText("Asal Kampus");

        ipk.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        ipk.setText("IPK");

        FP.setFont(new java.awt.Font("News706 BT", 1, 11)); // NOI18N
        FP.setText("Form Penilaian (0-100)");

        porto.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        porto.setText("Portofolio");

        proto.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        proto.setText("Prototyping");

        creativity.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        creativity.setText("Creativity");

        inputNama.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N

        inputKampus.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N

        inputIpk.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N

        inputPorto.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N

        inputProto.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N

        inputCreativity.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N

        nilai.setFont(new java.awt.Font("Bahnschrift", 1, 11)); // NOI18N
        nilai.setText("Cek Nilai");
        nilai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nilaiActionPerformed(evt);
            }
        });

        kembali.setFont(new java.awt.Font("Bahnschrift", 1, 11)); // NOI18N
        kembali.setText("Kembali");
        kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(creativity)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(proto)
                    .addComponent(porto)
                    .addComponent(ipk)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FP)
                            .addComponent(BCP)
                            .addComponent(kampus)
                            .addComponent(nama))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(inputPorto)
                    .addComponent(inputProto)
                    .addComponent(inputCreativity, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                    .addComponent(inputKampus)
                    .addComponent(inputIpk)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(SD))
                    .addComponent(inputNama))
                .addGap(33, 33, 33))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(nilai)
                .addGap(38, 38, 38)
                .addComponent(kembali)
                .addContainerGap(129, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SD)
                .addGap(37, 37, 37)
                .addComponent(BCP)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nama)
                    .addComponent(inputNama, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(kampus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ipk)
                            .addComponent(inputIpk, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addComponent(FP)
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(porto)
                            .addComponent(inputPorto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(proto)
                            .addComponent(inputProto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(creativity)
                            .addComponent(inputCreativity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nilai)
                            .addComponent(kembali))
                        .addGap(25, 25, 25))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(inputKampus, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 106, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nilaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nilaiActionPerformed
        // TODO add your handling code here:
        try {
            String nama = inputNama.getText();
            String kampus = inputKampus.getText();
            String ipk = inputIpk.getText();
            
            double porto = Double.parseDouble(inputPorto.getText());
            double proto = Double.parseDouble(inputProto.getText());
            double creativity = Double.parseDouble(inputCreativity.getText());
            
            double nilaiPorto = porto * 60/100;
            double nilaiProto = proto * 15/100;
            double nilaiCreativity = creativity * 25/100;
            
            double nilaiakhir = nilaiPorto+nilaiProto+nilaiCreativity;
            
            String keterangan;
            if (nilaiakhir >= 85){
                keterangan = "DITERIMA";
            } else {
                keterangan = "TIDAK DITERIMA";
            }
            
            HasilSeleksiDesigner hsd = new HasilSeleksiDesigner(nama,kampus,ipk,nilaiakhir,keterangan);
            hsd.setVisible(true);
            this.dispose();
        } catch (NumberFormatException ex){
            JOptionPane.showMessageDialog(this, "Input Tidak Valid", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_nilaiActionPerformed

    private void kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliActionPerformed
        // TODO add your handling code here:
        MenuAplikasi ma = new MenuAplikasi();
        ma.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_kembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Designer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Designer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Designer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Designer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Designer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BCP;
    private javax.swing.JLabel FP;
    private javax.swing.JLabel SD;
    private javax.swing.JLabel creativity;
    private javax.swing.JTextField inputCreativity;
    private javax.swing.JTextField inputIpk;
    private javax.swing.JTextField inputKampus;
    private javax.swing.JTextField inputNama;
    private javax.swing.JTextField inputPorto;
    private javax.swing.JTextField inputProto;
    private javax.swing.JLabel ipk;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel kampus;
    private javax.swing.JButton kembali;
    private javax.swing.JLabel nama;
    private javax.swing.JButton nilai;
    private javax.swing.JLabel porto;
    private javax.swing.JLabel proto;
    // End of variables declaration//GEN-END:variables
}
