/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasiseleksi;

/**
 *
 * @author Lab Informatika
 */
public class HasilSeleksiDesigner extends javax.swing.JFrame {

    /**
     * Creates new form HasilSeleksiDesigner
     */
    public HasilSeleksiDesigner() {
        initComponents();
        setLocationRelativeTo(null); 
    }
    
    HasilSeleksiDesigner(String nama, String kampus, String ipk, double nilaiakhir, String keterangan){
        this();
        
        hasilNama.setText(nama);
        hasilKampus.setText(kampus);
        hasilIpk.setText(ipk);
        
        hasilNilaiAkhir.setText(String.valueOf(nilaiakhir));
        hasilKet.setText(keterangan);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        HP = new javax.swing.JLabel();
        hasilBCP = new javax.swing.JLabel();
        nama = new javax.swing.JLabel();
        kampus = new javax.swing.JLabel();
        ipk = new javax.swing.JLabel();
        RP = new javax.swing.JLabel();
        nilaiakhir = new javax.swing.JLabel();
        keterangan = new javax.swing.JLabel();
        hasilNama = new javax.swing.JLabel();
        hasilKampus = new javax.swing.JLabel();
        hasilIpk = new javax.swing.JLabel();
        hasilNilaiAkhir = new javax.swing.JLabel();
        hasilKet = new javax.swing.JLabel();
        kembali = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        HP.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        HP.setText("Hasil Penilaian");

        hasilBCP.setFont(new java.awt.Font("News706 BT", 1, 11)); // NOI18N
        hasilBCP.setText("Biodata Calon Pegawai");

        nama.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        nama.setText("Nama");

        kampus.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        kampus.setText("Asal Kampus");

        ipk.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        ipk.setText("IPK");

        RP.setFont(new java.awt.Font("News706 BT", 1, 11)); // NOI18N
        RP.setText("Result Penilaian (0-100)");

        nilaiakhir.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        nilaiakhir.setText("Nilai Akhir");

        keterangan.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        keterangan.setText("Keterangan");

        hasilNama.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N

        hasilKampus.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N

        hasilIpk.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N

        hasilNilaiAkhir.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N

        hasilKet.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N

        kembali.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        kembali.setText("Kembali");
        kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(hasilBCP))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(RP))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nama)
                            .addComponent(kampus)
                            .addComponent(ipk)
                            .addComponent(nilaiakhir)
                            .addComponent(keterangan))
                        .addGap(109, 109, 109)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(hasilNama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(hasilKampus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(hasilIpk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(hasilNilaiAkhir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(hasilKet, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(HP)
                            .addComponent(kembali))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(HP)
                .addGap(18, 18, 18)
                .addComponent(hasilBCP)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(nama)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(kampus)
                        .addGap(11, 11, 11)
                        .addComponent(ipk)
                        .addGap(30, 30, 30)
                        .addComponent(RP)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nilaiakhir)
                            .addComponent(hasilNilaiAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(keterangan)
                            .addComponent(hasilKet, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(hasilNama, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hasilKampus, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hasilIpk, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(kembali)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliActionPerformed
        // TODO add your handling code here:
        MenuAplikasi ma = new MenuAplikasi();
        ma.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_kembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HasilSeleksiDesigner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HasilSeleksiDesigner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HasilSeleksiDesigner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HasilSeleksiDesigner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HasilSeleksiDesigner().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel HP;
    private javax.swing.JLabel RP;
    private javax.swing.JLabel hasilBCP;
    private javax.swing.JLabel hasilIpk;
    private javax.swing.JLabel hasilKampus;
    private javax.swing.JLabel hasilKet;
    private javax.swing.JLabel hasilNama;
    private javax.swing.JLabel hasilNilaiAkhir;
    private javax.swing.JLabel ipk;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel kampus;
    private javax.swing.JButton kembali;
    private javax.swing.JLabel keterangan;
    private javax.swing.JLabel nama;
    private javax.swing.JLabel nilaiakhir;
    // End of variables declaration//GEN-END:variables
}
